name: Weerwolven
version: '1.0'
main: nl.multitime.weerwolven.Weerwolven
api-version: '1.19'
authors: [ MysticPhoenix_ ]
description: Weerwolven van Wakkerdam gamemode voor Minecraft

commands:
  weerwolven:
    description: Main command for Weerwolven gamemode
    aliases: [ww, werewolf]
    usage: /weerwolven <subcommand>
